# Generated by Django 5.2.8 on 2026-03-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamp_app', '0007_telegram_prod_ready'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telegramlinktoken',
            new_name='pamp_app_te_user_id_b62597_idx',
            old_name='pamp_app_te_user_id_9d18b7_idx',
        ),
    ]
