[mypy]
python_version = 3.13
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
no_implicit_optional = True
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = pampApp.settings

[mypy-pamp_app.*]
disallow_untyped_defs = True
disallow_incomplete_defs = True
